


/*   Given the existing code below, can you write some code so that their values are switched around? */


var  a="3";
var b="8";


/* So that the variable  a hold the value "8".
And the variable   b holds the value "3".
When the code is run, it should output:

a is 8
b is 3


Do Not change any of the existing code.
You are Not allowed to type any numbers.
You should Not redeclare the variable a and b.






/*  solution */



var c=a;
a=b;
b=c;
